using Essensplan.Web.Data;
using Essensplan.Web.Models;
using Microsoft.EntityFrameworkCore;

namespace Essensplan.Web.Services;

public class WeekPlanService
{
    private static readonly MealType[] PlannedMealTypes = { MealType.Fruehstueck, MealType.Mittagessen, MealType.Abendessen };
    private const int RepeatAvoidanceDays = 13;

    private readonly IDbContextFactory<AppDbContext> _dbFactory;
    private readonly WeekPlanChangeNotifier _notifier;

    public WeekPlanService(IDbContextFactory<AppDbContext> dbFactory, WeekPlanChangeNotifier notifier)
    {
        _dbFactory = dbFactory;
        _notifier = notifier;
    }

    public static DateOnly GetMonday(DateOnly anyDate)
    {
        var diff = ((int)anyDate.DayOfWeek - (int)DayOfWeek.Monday + 7) % 7;
        return anyDate.AddDays(-diff);
    }

    public async Task<WeekPlan> GetOrCreateWeekAsync(DateOnly monday, int householdId)
    {
        await using var db = await _dbFactory.CreateDbContextAsync();

        var week = await db.WeekPlans
            .Include(w => w.Entries.OrderBy(e => e.Date).ThenBy(e => e.MealType))
            .ThenInclude(e => e.Menu)
            .FirstOrDefaultAsync(w => w.StartDate == monday && w.HouseholdId == householdId);

        if (week is null)
        {
            week = new WeekPlan { StartDate = monday, HouseholdId = householdId };
            db.WeekPlans.Add(week);
            await db.SaveChangesAsync();
        }

        var existingSlots = week.Entries.Select(e => (e.Date, e.MealType)).ToHashSet();
        var missing = new List<WeekPlanEntry>();

        for (var i = 0; i < 7; i++)
        {
            var date = monday.AddDays(i);
            foreach (var mealType in PlannedMealTypes)
            {
                if (!existingSlots.Contains((date, mealType)))
                    missing.Add(new WeekPlanEntry { WeekPlanId = week.Id, Date = date, MealType = mealType });
            }
        }

        if (missing.Count > 0)
        {
            db.WeekPlanEntries.AddRange(missing);
            await db.SaveChangesAsync();

            week = await db.WeekPlans
                .Include(w => w.Entries.OrderBy(e => e.Date).ThenBy(e => e.MealType))
                .ThenInclude(e => e.Menu)
                .FirstAsync(w => w.Id == week.Id);
        }

        return week;
    }

    public async Task AssignMenuAsync(int entryId, int? menuId, int householdId)
    {
        await using var db = await _dbFactory.CreateDbContextAsync();
        var entry = await db.WeekPlanEntries
            .Include(e => e.WeekPlan)
            .FirstOrDefaultAsync(e => e.Id == entryId && e.WeekPlan.HouseholdId == householdId);
        if (entry is null) return;

        entry.MenuId = menuId;
        entry.IsAutoGenerated = false;
        await db.SaveChangesAsync();
        await _notifier.NotifyAsync(householdId);
    }

    public async Task ClearWeekAsync(int weekPlanId, int householdId)
    {
        await using var db = await _dbFactory.CreateDbContextAsync();
        var week = await db.WeekPlans.FirstOrDefaultAsync(w => w.Id == weekPlanId && w.HouseholdId == householdId);
        if (week is null) return;

        var entries = await db.WeekPlanEntries.Where(e => e.WeekPlanId == weekPlanId).ToListAsync();
        foreach (var entry in entries)
        {
            entry.MenuId = null;
            entry.IsAutoGenerated = false;
        }
        await db.SaveChangesAsync();
        await _notifier.NotifyAsync(householdId);
    }

    public async Task<int> AutoGenerateAsync(int weekPlanId, bool overwriteExisting = false, ISet<MealType>? slotsToFill = null, int householdId = 0)
    {
        await using var db = await _dbFactory.CreateDbContextAsync();

        var week = await db.WeekPlans
            .Include(w => w.Entries)
            .FirstOrDefaultAsync(w => w.Id == weekPlanId && w.HouseholdId == householdId);

        if (week is null) return 0;

        var allMenus = await db.Menus.Where(m => m.HouseholdId == householdId).AsNoTracking().ToListAsync();
        if (allMenus.Count == 0) return 0;

        var recentCutoff = week.StartDate.AddDays(-RepeatAvoidanceDays);
        var futureCutoff = week.StartDate.AddDays(7 + RepeatAvoidanceDays);
        var recentlyUsedMenuIds = await db.WeekPlanEntries
            .Where(e => e.MenuId != null
                     && e.WeekPlanId != weekPlanId
                     && e.WeekPlan.HouseholdId == householdId
                     && e.Date >= recentCutoff
                     && e.Date < futureCutoff)
            .Select(e => e.MenuId!.Value)
            .ToListAsync();
        var recentSet = recentlyUsedMenuIds.ToHashSet();

        var rng = Random.Shared;
        var usedThisRun = new HashSet<int>();
        var filled = 0;

        var targets = week.Entries.Where(e => overwriteExisting || e.MenuId is null).OrderBy(e => e.Date).ToList();

        foreach (var entry in targets)
        {
            if (slotsToFill is not null && !slotsToFill.Contains(entry.MealType)) continue;

            var bit = MealTypeFlags.From(entry.MealType);
            var candidates = allMenus.Where(m => (m.AllowedMealTypes & bit) != 0).ToList();
            if (candidates.Count == 0) continue;

            var pool = candidates.Where(m => !recentSet.Contains(m.Id) && !usedThisRun.Contains(m.Id)).ToList();
            if (pool.Count == 0)
                pool = candidates.Where(m => !usedThisRun.Contains(m.Id)).ToList();
            if (pool.Count == 0)
                pool = candidates;

            var chosen = pool[rng.Next(pool.Count)];
            entry.MenuId = chosen.Id;
            entry.IsAutoGenerated = true;
            usedThisRun.Add(chosen.Id);
            filled++;
        }

        await db.SaveChangesAsync();
        if (filled > 0) await _notifier.NotifyAsync(householdId);
        return filled;
    }
}
