using Essensplan.Web.Data;
using Essensplan.Web.Models;
using Microsoft.EntityFrameworkCore;

namespace Essensplan.Web.Services;

public class WeekPlanService
{
    private static readonly MealType[] PlannedMealTypes = { MealType.Fruehstueck, MealType.Mittagessen, MealType.Abendessen };

    /// <summary>How many days back a menu must not have appeared to be eligible again during auto-generation.</summary>
    private const int RepeatAvoidanceDays = 13;

    private readonly IDbContextFactory<AppDbContext> _dbFactory;

    public WeekPlanService(IDbContextFactory<AppDbContext> dbFactory)
    {
        _dbFactory = dbFactory;
    }

    public static DateOnly GetMonday(DateOnly anyDate)
    {
        var diff = ((int)anyDate.DayOfWeek - (int)DayOfWeek.Monday + 7) % 7;
        return anyDate.AddDays(-diff);
    }

    public async Task<WeekPlan> GetOrCreateWeekAsync(DateOnly monday)
    {
        await using var db = await _dbFactory.CreateDbContextAsync();

        var week = await db.WeekPlans
            .Include(w => w.Entries.OrderBy(e => e.Date).ThenBy(e => e.MealType))
            .ThenInclude(e => e.Menu)
            .FirstOrDefaultAsync(w => w.StartDate == monday);

        if (week is null)
        {
            week = new WeekPlan { StartDate = monday };
            db.WeekPlans.Add(week);
            await db.SaveChangesAsync();
        }

        var existingSlots = week.Entries.Select(e => (e.Date, e.MealType)).ToHashSet();
        var missing = new List<WeekPlanEntry>();

        for (var i = 0; i < 7; i++)
        {
            var date = monday.AddDays(i);
            foreach (var mealType in PlannedMealTypes)
            {
                if (!existingSlots.Contains((date, mealType)))
                {
                    missing.Add(new WeekPlanEntry { WeekPlanId = week.Id, Date = date, MealType = mealType });
                }
            }
        }

        if (missing.Count > 0)
        {
            db.WeekPlanEntries.AddRange(missing);
            await db.SaveChangesAsync();

            week = await db.WeekPlans
                .Include(w => w.Entries.OrderBy(e => e.Date).ThenBy(e => e.MealType))
                .ThenInclude(e => e.Menu)
                .FirstAsync(w => w.Id == week.Id);
        }

        return week;
    }

    public async Task AssignMenuAsync(int entryId, int? menuId)
    {
        await using var db = await _dbFactory.CreateDbContextAsync();
        var entry = await db.WeekPlanEntries.FindAsync(entryId);
        if (entry is null) return;

        entry.MenuId = menuId;
        entry.IsAutoGenerated = false;
        await db.SaveChangesAsync();
    }

    public async Task ClearWeekAsync(int weekPlanId)
    {
        await using var db = await _dbFactory.CreateDbContextAsync();
        var entries = await db.WeekPlanEntries.Where(e => e.WeekPlanId == weekPlanId).ToListAsync();
        foreach (var entry in entries)
        {
            entry.MenuId = null;
            entry.IsAutoGenerated = false;
        }
        await db.SaveChangesAsync();
    }

    /// <summary>
    /// Fills empty slots (or all slots when overwrite=true) of a week with randomly chosen menus,
    /// preferring menus that have not appeared in the past <see cref="RepeatAvoidanceDays"/> days.
    /// </summary>
    public async Task<int> AutoGenerateAsync(int weekPlanId, bool overwriteExisting = false)
    {
        await using var db = await _dbFactory.CreateDbContextAsync();

        var week = await db.WeekPlans
            .Include(w => w.Entries)
            .FirstOrDefaultAsync(w => w.Id == weekPlanId);

        if (week is null) return 0;

        var allMenus = await db.Menus.AsNoTracking().ToListAsync();
        if (allMenus.Count == 0) return 0;

        var menusByMeal = allMenus.GroupBy(m => m.MealType).ToDictionary(g => g.Key, g => g.ToList());

        var recentCutoff = week.StartDate.AddDays(-RepeatAvoidanceDays);
        var futureCutoff = week.StartDate.AddDays(7 + RepeatAvoidanceDays);
        var recentlyUsedMenuIds = await db.WeekPlanEntries
            .Where(e => e.MenuId != null && e.WeekPlanId != weekPlanId && e.Date >= recentCutoff && e.Date < futureCutoff)
            .Select(e => e.MenuId!.Value)
            .ToListAsync();
        var recentSet = recentlyUsedMenuIds.ToHashSet();

        var rng = Random.Shared;
        var usedThisRun = new HashSet<int>();
        var filled = 0;

        var targets = week.Entries.Where(e => overwriteExisting || e.MenuId is null).OrderBy(e => e.Date).ToList();

        foreach (var entry in targets)
        {
            if (!menusByMeal.TryGetValue(entry.MealType, out var candidates) || candidates.Count == 0)
            {
                continue;
            }

            var pool = candidates.Where(m => !recentSet.Contains(m.Id) && !usedThisRun.Contains(m.Id)).ToList();
            if (pool.Count == 0)
            {
                pool = candidates.Where(m => !usedThisRun.Contains(m.Id)).ToList();
            }
            if (pool.Count == 0)
            {
                pool = candidates;
            }

            var chosen = pool[rng.Next(pool.Count)];
            entry.MenuId = chosen.Id;
            entry.IsAutoGenerated = true;
            usedThisRun.Add(chosen.Id);
            filled++;
        }

        await db.SaveChangesAsync();
        return filled;
    }
}
