using System.ComponentModel.DataAnnotations;

namespace Essensplan.Web.Models;

/// <summary>One slot in a week plan: a specific day + meal type, optionally filled with a menu.</summary>
public class WeekPlanEntry
{
    public int Id { get; set; }

    public int WeekPlanId { get; set; }
    public WeekPlan? WeekPlan { get; set; }

    public DateOnly Date { get; set; }

    public MealType MealType { get; set; }

    public int? MenuId { get; set; }
    public Menu? Menu { get; set; }

    /// <summary>True when this slot was filled by the auto-generator rather than a manual pick.</summary>
    public bool IsAutoGenerated { get; set; }

    [StringLength(300)]
    public string? Notes { get; set; }
}
